logging:
    level:
        tk.mybatis: DEBUG
        com.guludai.admin: DEBUG
  #  config: classpath:logback.xml
    path: /guludai-cmp
    
server:
    port: 8703
    
spring:
    application:
        name: guludai-cmp
    boot:
        admin:
             url: http://localhost:8762
    datasource:
        name: gld_monitor
        url: jdbc:mysql://localhost:3306/ag_admin?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    basepackage: com.guludai.admin.mapper
    xmlLocation: classpath:mapper/**/*.xml

eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/