spring:
    application:
        name: guludai-aget-cmp
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
server:
    port: 8902 #启动端口

zuul:
  #prefix: /techouse #为zuul设置一个公共的前缀
  #ignoredServices: '*'
  routes:
    guludai-cmp-ui: 
      path: /admin/** 
      serviceId: guludai-cmp-ui
    guludai-cmp:
      path: /back/**
      serviceId: guludai-cmp

ribbon:
  eureka:
    enabled: false #配置zuul路由时用将此属性设置为false

guludai-cmp-ui:
  ribbon:
    listOfServers: 127.0.0.1:8801 
guludai-cmp:
  ribbon:
    listOfServers: 127.0.0.1:8703

eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
security:
    user:
        name: admin
        password: admin
        role: USER